# Case loader for OPF project
# This file handles loading and validation of case studies

using CSV
using DataFrames
using JSON3

"""
    load_case(case_name::String)

Load a case study from the cases directory.

# Arguments
- `case_name::String`: Name of the case to load

# Returns
- Dictionary containing case data or nothing if case not found
"""
function load_case(case_name::String)
    # Construct the case path
    case_path = joinpath("casos", case_name)
    
    # Check if case exists
    if !isdir(case_path)
        println("Error: Case '$case_name' not found in directory '$case_path'")
        return nothing
    end
    
    # Load case data
    case_data = Dict()
    
    # Load generator data
    gen_file = joinpath(case_path, "datosGeneradores.csv")
    if isfile(gen_file)
        case_data["generators"] = CSV.read(gen_file, DataFrame)
    end
    
    # Load line data
    line_file = joinpath(case_path, "datosLineas.csv")
    if isfile(line_file)
        case_data["lines"] = CSV.read(line_file, DataFrame)
    end
    
    # Load node data
    node_file = joinpath(case_path, "datosNodos.csv")
    if isfile(node_file)
        case_data["nodes"] = CSV.read(node_file, DataFrame)
    end
    
    # Imprimir información del caso cargado
    println("=== INFORMACIÓN DEL CASO CARGADO ===")
    println("Caso: $case_name")
    println()
    
    if haskey(case_data, "generators")
        println("📊 DATOS DE GENERADORES:")
        println("   Número de generadores: $(nrow(case_data["generators"]))")
        println("   Columnas: $(names(case_data["generators"]))")
        println("   Primeras filas:")
        println(case_data["generators"][1:min(3, nrow(case_data["generators"])), :])
        println()
    end
    
    if haskey(case_data, "lines")
        println("🔌 DATOS DE LÍNEAS:")
        println("   Número de líneas: $(nrow(case_data["lines"]))")
        println("   Columnas: $(names(case_data["lines"]))")
        println("   Primeras filas:")
        println(case_data["lines"][1:min(3, nrow(case_data["lines"])), :])
        println()
    end
    
    if haskey(case_data, "nodes")
        println("🏢 DATOS DE NODOS:")
        println("   Número de nodos: $(nrow(case_data["nodes"]))")
        println("   Columnas: $(names(case_data["nodes"]))")
        println("   Primeras filas:")
        println(case_data["nodes"][1:min(3, nrow(case_data["nodes"])), :])
        println()
    end
    
    println("✅ Caso cargado exitosamente")
    println()
    
    return case_data
end

"""
    list_available_cases()

List all available cases in the cases directory.

# Returns
- Array of case names
"""
function list_available_cases()
    cases_dir = "casos"
    if !isdir(cases_dir)
        return String[]
    end
    
    return [d for d in readdir(cases_dir) if isdir(joinpath(cases_dir, d))]
end

"""
    validate_case(case_data::Dict)

Validate that a case has all required data.

# Arguments
- `case_data::Dict`: Case data to validate

# Returns
- Boolean indicating if case is valid
"""
function validate_case(case_data::Dict)
    required_keys = ["generators", "lines", "nodes"]
    
    for key in required_keys
        if !haskey(case_data, key)
            println("Error: Missing required data '$key'")
            return false
        end
    end
    
    return true
end

"""
    load_case_json(json_path::String)

Load a case study from a JSON file generated by the case converter.

# Arguments
- `json_path::String`: Path to the JSON file to load

# Returns
- Dictionary containing case data with keys "generators", "lines", "nodes" (DataFrames)
- Returns nothing if file not found or invalid
"""
function load_case_json(json_path::String)
    if !isfile(json_path)
        println("Error: JSON file '$json_path' not found")
        return nothing
    end

    try
        # Read the JSON file
        json_content = read(json_path, String)
        json_data = JSON3.read(json_content)

        # Map JSON keys to expected keys
        key_map = Dict(
            "datosGeneradores" => "generators",
            "datosLineas"      => "lines",
            "datosNodos"       => "nodes"
        )

        case_data = Dict{String, DataFrame}()

        for (json_key, out_key) in key_map
            if haskey(json_data, json_key)
                # Convert JSON object with row dictionaries to DataFrame
                json_section = json_data[json_key]
                
                # Collect all rows into a vector of dictionaries
                rows = []
                for (row_key, row_data) in json_section
                    # Create a dictionary for this row
                    row_dict = Dict{String, Any}()
                    
                    # Add all columns from the row data
                    for (col_name, col_value) in row_data
                        row_dict[col_name] = col_value
                    end
                    
                    push!(rows, row_dict)
                end
                
                # Convert to DataFrame
                if !isempty(rows)
                    df = DataFrame(rows)
                    case_data[out_key] = df
                end
            end
        end

        # Imprimir información del caso cargado
        println("=== INFORMACIÓN DEL CASO CARGADO (JSON) ===")
        println("Archivo: $json_path")
        println()
        
        if haskey(case_data, "generators")
            println("📊 DATOS DE GENERADORES:")
            println("   Número de generadores: $(nrow(case_data["generators"]))")
            println("   Columnas: $(names(case_data["generators"]))")
            println("   Primeras filas:")
            println(case_data["generators"][1:min(3, nrow(case_data["generators"])), :])
            println()
        end
        
        if haskey(case_data, "lines")
            println("🔌 DATOS DE LÍNEAS:")
            println("   Número de líneas: $(nrow(case_data["lines"]))")
            println("   Columnas: $(names(case_data["lines"]))")
            println("   Primeras filas:")
            println(case_data["lines"][1:min(3, nrow(case_data["lines"])), :])
            println()
        end
        
        if haskey(case_data, "nodes")
            println("🏢 DATOS DE NODOS:")
            println("   Número de nodos: $(nrow(case_data["nodes"]))")
            println("   Columnas: $(names(case_data["nodes"]))")
            println("   Primeras filas:")
            println(case_data["nodes"][1:min(3, nrow(case_data["nodes"])), :])
            println()
        end
        
        println("✅ Caso JSON cargado exitosamente")
        println()

        return case_data
    catch e
        println("Error reading JSON file: $e")
        return nothing
    end
end

# Start the application
if abspath(PROGRAM_FILE) == @__FILE__
    # Probar con un archivo JSON válido
    json_path = "cases_json/red_3Nodos_aleatorio_1.json"
    println("Probando con: $json_path")
    case_data = load_case_json(json_path)
    if case_data !== nothing
        println("✅ Caso cargado correctamente")
    else
        println("❌ Error al cargar el caso")
    end
end